# Generated by Django 3.2.4 on 2021-06-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cliente_colaborador_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.colaborador'),
        ),
    ]
