# Generated by Django 3.2.4 on 2021-06-11 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pedido_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='subtotal',
        ),
    ]
