# Generated by Django 3.2.4 on 2021-06-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_productoimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tarifa',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
